/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package estru2proyecto;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.TableView.TableRow;

/**
 *
 * @author samue
 */
public class Estru2Proyect extends javax.swing.JFrame {

    /**
     * Creates new form Estru2Proyect
     */
    public Estru2Proyect() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Archivos = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jb_Archivos1 = new javax.swing.JButton();
        jb_Campos1 = new javax.swing.JButton();
        jb_Registros1 = new javax.swing.JButton();
        jb_Indices1 = new javax.swing.JButton();
        jb_CerrarPrograma1 = new javax.swing.JButton();
        jd_CrearCampos = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jrb_llavePrimaria1 = new javax.swing.JRadioButton();
        jrb_llavePrimaria2 = new javax.swing.JRadioButton();
        jrb_llavePrimaria3 = new javax.swing.JRadioButton();
        jrb_llavePrimaria4 = new javax.swing.JRadioButton();
        jrb_llavePrimaria5 = new javax.swing.JRadioButton();
        jrb_llavePrimaria6 = new javax.swing.JRadioButton();
        jrb_llavePrimaria7 = new javax.swing.JRadioButton();
        jrb_llavePrimaria8 = new javax.swing.JRadioButton();
        jrb_llavePrimaria9 = new javax.swing.JRadioButton();
        jrb_llavePrimaria10 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jtf_NomCampo1 = new javax.swing.JTextField();
        jtf_NomCampo2 = new javax.swing.JTextField();
        jtf_NomCampo3 = new javax.swing.JTextField();
        jtf_NomCampo4 = new javax.swing.JTextField();
        jtf_NomCampo5 = new javax.swing.JTextField();
        jtf_NomCampo6 = new javax.swing.JTextField();
        jtf_NomCampo7 = new javax.swing.JTextField();
        jtf_NomCampo8 = new javax.swing.JTextField();
        jtf_NomCampo9 = new javax.swing.JTextField();
        jtf_NomCampo10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        js_longitud1 = new javax.swing.JSpinner();
        js_longitud2 = new javax.swing.JSpinner();
        js_longitud3 = new javax.swing.JSpinner();
        js_longitud4 = new javax.swing.JSpinner();
        js_longitud5 = new javax.swing.JSpinner();
        js_longitud6 = new javax.swing.JSpinner();
        js_longitud7 = new javax.swing.JSpinner();
        js_longitud8 = new javax.swing.JSpinner();
        js_longitud9 = new javax.swing.JSpinner();
        js_longitud10 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jcb_tipoDato1 = new javax.swing.JComboBox<>();
        jcb_tipoDato2 = new javax.swing.JComboBox<>();
        jcb_tipoDato3 = new javax.swing.JComboBox<>();
        jcb_tipoDato4 = new javax.swing.JComboBox<>();
        jcb_tipoDato5 = new javax.swing.JComboBox<>();
        jcb_tipoDato6 = new javax.swing.JComboBox<>();
        jcb_tipoDato7 = new javax.swing.JComboBox<>();
        jcb_tipoDato8 = new javax.swing.JComboBox<>();
        jcb_tipoDato9 = new javax.swing.JComboBox<>();
        jcb_tipoDato10 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jb_GuardarCampos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jd_Campos = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jb_crearCampo = new javax.swing.JButton();
        jb_Campos2 = new javax.swing.JButton();
        jb_Registros2 = new javax.swing.JButton();
        jb_Indices2 = new javax.swing.JButton();
        jb_CerrarPrograma2 = new javax.swing.JButton();
        jp_CrearCampos = new javax.swing.JPanel();
        jp_ListarCampos = new javax.swing.JPanel();
        jp_ModificarCampos = new javax.swing.JPanel();
        jp_BorrarCampos = new javax.swing.JPanel();
        jp_Vacio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_Borrar = new javax.swing.JList<>();
        jb_borrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_ModificarCampos = new javax.swing.JList<>();
        jb_ModificarCampos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_ListarCampos = new javax.swing.JTable();
        jtf_NomCampo = new javax.swing.JTextField();
        jb_CrearCampo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcb_tipoDato = new javax.swing.JComboBox<>();
        jcb_llavePrimaria = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        js_longitud = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jb_Archivos = new javax.swing.JButton();
        jb_Campos = new javax.swing.JButton();
        jb_Registros = new javax.swing.JButton();
        jb_Indices = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jb_CerrarPrograma = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(127, 127, 186));

        jb_Archivos1.setBackground(new java.awt.Color(125, 125, 241));
        jb_Archivos1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_Archivos1.setForeground(new java.awt.Color(22, 22, 79));
        jb_Archivos1.setText("Crear Archivo");
        jb_Archivos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_Archivos1MouseClicked(evt);
            }
        });
        jb_Archivos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Archivos1ActionPerformed(evt);
            }
        });
        jb_Archivos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_Archivos1KeyPressed(evt);
            }
        });

        jb_Campos1.setBackground(new java.awt.Color(125, 125, 241));
        jb_Campos1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_Campos1.setForeground(new java.awt.Color(22, 22, 79));
        jb_Campos1.setText("M");

        jb_Registros1.setBackground(new java.awt.Color(125, 125, 241));
        jb_Registros1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_Registros1.setForeground(new java.awt.Color(22, 22, 79));
        jb_Registros1.setText("Registros");

        jb_Indices1.setBackground(new java.awt.Color(125, 125, 241));
        jb_Indices1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_Indices1.setForeground(new java.awt.Color(22, 22, 79));
        jb_Indices1.setText("Indices");

        jb_CerrarPrograma1.setBackground(new java.awt.Color(206, 115, 121));
        jb_CerrarPrograma1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_CerrarPrograma1.setForeground(new java.awt.Color(130, 49, 54));
        jb_CerrarPrograma1.setText("Cerrar Programa");
        jb_CerrarPrograma1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CerrarPrograma1MouseClicked(evt);
            }
        });
        jb_CerrarPrograma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CerrarPrograma1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jb_Archivos1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Campos1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Registros1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Indices1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(277, 277, 277))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_CerrarPrograma1)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_CerrarPrograma1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jb_Archivos1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Campos1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Registros1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Indices1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout jd_ArchivosLayout = new javax.swing.GroupLayout(jd_Archivos.getContentPane());
        jd_Archivos.getContentPane().setLayout(jd_ArchivosLayout);
        jd_ArchivosLayout.setHorizontalGroup(
            jd_ArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_ArchivosLayout.setVerticalGroup(
            jd_ArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(127, 127, 186));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jrb_llavePrimaria1);
        jrb_llavePrimaria1.setSelected(true);
        jPanel3.add(jrb_llavePrimaria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        buttonGroup1.add(jrb_llavePrimaria2);
        jrb_llavePrimaria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_llavePrimaria2ActionPerformed(evt);
            }
        });
        jPanel3.add(jrb_llavePrimaria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        buttonGroup1.add(jrb_llavePrimaria3);
        jPanel3.add(jrb_llavePrimaria3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        buttonGroup1.add(jrb_llavePrimaria4);
        jPanel3.add(jrb_llavePrimaria4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        buttonGroup1.add(jrb_llavePrimaria5);
        jPanel3.add(jrb_llavePrimaria5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        buttonGroup1.add(jrb_llavePrimaria6);
        jPanel3.add(jrb_llavePrimaria6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        buttonGroup1.add(jrb_llavePrimaria7);
        jPanel3.add(jrb_llavePrimaria7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        buttonGroup1.add(jrb_llavePrimaria8);
        jPanel3.add(jrb_llavePrimaria8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        buttonGroup1.add(jrb_llavePrimaria9);
        jPanel3.add(jrb_llavePrimaria9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        buttonGroup1.add(jrb_llavePrimaria10);
        jPanel3.add(jrb_llavePrimaria10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Llave primaria");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jtf_NomCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampo1ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf_NomCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 218, -1));

        jtf_NomCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampo2ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf_NomCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 218, -1));

        jtf_NomCampo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampo3ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf_NomCampo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 218, -1));

        jtf_NomCampo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampo4ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf_NomCampo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 218, -1));

        jtf_NomCampo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampo5ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf_NomCampo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 218, -1));

        jtf_NomCampo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampo6ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf_NomCampo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 218, -1));

        jtf_NomCampo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampo7ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf_NomCampo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 218, -1));

        jtf_NomCampo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampo8ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf_NomCampo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 218, -1));

        jtf_NomCampo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampo9ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf_NomCampo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 218, -1));

        jtf_NomCampo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampo10ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf_NomCampo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 218, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre de Campo");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 112, -1));
        jPanel3.add(js_longitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));
        jPanel3.add(js_longitud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));
        jPanel3.add(js_longitud3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));
        jPanel3.add(js_longitud4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));
        jPanel3.add(js_longitud5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));
        jPanel3.add(js_longitud6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));
        jPanel3.add(js_longitud7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));
        jPanel3.add(js_longitud8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));
        jPanel3.add(js_longitud9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));
        jPanel3.add(js_longitud10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Longitud");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jcb_tipoDato1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jPanel3.add(jcb_tipoDato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jcb_tipoDato2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jPanel3.add(jcb_tipoDato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jcb_tipoDato3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jPanel3.add(jcb_tipoDato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jcb_tipoDato4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jPanel3.add(jcb_tipoDato4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jcb_tipoDato5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jPanel3.add(jcb_tipoDato5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jcb_tipoDato6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jPanel3.add(jcb_tipoDato6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jcb_tipoDato7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jPanel3.add(jcb_tipoDato7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jcb_tipoDato8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jPanel3.add(jcb_tipoDato8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jcb_tipoDato9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jPanel3.add(jcb_tipoDato9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        jcb_tipoDato10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));
        jPanel3.add(jcb_tipoDato10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo de Dato");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Crear Campos");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jb_GuardarCampos.setText("Guardar Campos");
        jb_GuardarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_GuardarCamposMouseClicked(evt);
            }
        });
        jb_GuardarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_GuardarCamposActionPerformed(evt);
            }
        });
        jPanel3.add(jb_GuardarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 150, 58));

        jButton1.setBackground(new java.awt.Color(206, 115, 121));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(130, 49, 54));
        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 6, 75, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 670, 20));

        javax.swing.GroupLayout jd_CrearCamposLayout = new javax.swing.GroupLayout(jd_CrearCampos.getContentPane());
        jd_CrearCampos.getContentPane().setLayout(jd_CrearCamposLayout);
        jd_CrearCamposLayout.setHorizontalGroup(
            jd_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        jd_CrearCamposLayout.setVerticalGroup(
            jd_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jb_crearCampo.setText("Crear Campos");
        jb_crearCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCampoMouseClicked(evt);
            }
        });
        jb_crearCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearCampoActionPerformed(evt);
            }
        });
        jb_crearCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_crearCampoKeyPressed(evt);
            }
        });

        jb_Campos2.setText("Listar");
        jb_Campos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Campos2ActionPerformed(evt);
            }
        });

        jb_Registros2.setText("Modificar");
        jb_Registros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Registros2ActionPerformed(evt);
            }
        });

        jb_Indices2.setText("Borrar");
        jb_Indices2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Indices2ActionPerformed(evt);
            }
        });

        jb_CerrarPrograma2.setText("Cerrar Programa");
        jb_CerrarPrograma2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CerrarPrograma2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_CerrarPrograma2)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jb_crearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Campos2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Registros2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Indices2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_CerrarPrograma2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jb_crearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Campos2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Registros2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Indices2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jp_CrearCampos.setBackground(new java.awt.Color(153, 153, 153));

        jp_ListarCampos.setBackground(new java.awt.Color(153, 153, 153));

        jp_ModificarCampos.setBackground(new java.awt.Color(153, 153, 153));

        jp_BorrarCampos.setBackground(new java.awt.Color(153, 153, 153));

        jp_Vacio.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jp_VacioLayout = new javax.swing.GroupLayout(jp_Vacio);
        jp_Vacio.setLayout(jp_VacioLayout);
        jp_VacioLayout.setHorizontalGroup(
            jp_VacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        jp_VacioLayout.setVerticalGroup(
            jp_VacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        jl_Borrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_Borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_BorrarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_Borrar);

        jb_borrar.setText("Borrar");
        jb_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_BorrarCamposLayout = new javax.swing.GroupLayout(jp_BorrarCampos);
        jp_BorrarCampos.setLayout(jp_BorrarCamposLayout);
        jp_BorrarCamposLayout.setHorizontalGroup(
            jp_BorrarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Vacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_BorrarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_BorrarCamposLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
            .addGroup(jp_BorrarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_BorrarCamposLayout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addComponent(jb_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(205, Short.MAX_VALUE)))
        );
        jp_BorrarCamposLayout.setVerticalGroup(
            jp_BorrarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Vacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_BorrarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_BorrarCamposLayout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(84, Short.MAX_VALUE)))
            .addGroup(jp_BorrarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_BorrarCamposLayout.createSequentialGroup()
                    .addGap(458, 458, 458)
                    .addComponent(jb_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        jl_ModificarCampos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_ModificarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_ModificarCamposMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_ModificarCampos);

        jb_ModificarCampos.setText("Modificar");
        jb_ModificarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModificarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_ModificarCamposLayout = new javax.swing.GroupLayout(jp_ModificarCampos);
        jp_ModificarCampos.setLayout(jp_ModificarCamposLayout);
        jp_ModificarCamposLayout.setHorizontalGroup(
            jp_ModificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_BorrarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_ModificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_ModificarCamposLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
            .addGroup(jp_ModificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_ModificarCamposLayout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(jb_ModificarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );
        jp_ModificarCamposLayout.setVerticalGroup(
            jp_ModificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_BorrarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_ModificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_ModificarCamposLayout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(84, Short.MAX_VALUE)))
            .addGroup(jp_ModificarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_ModificarCamposLayout.createSequentialGroup()
                    .addGap(456, 456, 456)
                    .addComponent(jb_ModificarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        jt_ListarCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo de Dato", "Longitud", "Llave Primaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_ListarCampos);

        javax.swing.GroupLayout jp_ListarCamposLayout = new javax.swing.GroupLayout(jp_ListarCampos);
        jp_ListarCampos.setLayout(jp_ListarCamposLayout);
        jp_ListarCamposLayout.setHorizontalGroup(
            jp_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_ModificarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_ListarCamposLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jp_ListarCamposLayout.setVerticalGroup(
            jp_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_ModificarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_ListarCamposLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        jtf_NomCampo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_NomCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_NomCampoActionPerformed(evt);
            }
        });

        jb_CrearCampo.setText("Crear");
        jb_CrearCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearCampoMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nombre de Campo");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jcb_tipoDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boolean", "String", "Integer", "Char ", "Double", "Float", "Short", "Byte" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Longitud");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tipo de Dato");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Llave Primaria?");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jp_CrearCamposLayout = new javax.swing.GroupLayout(jp_CrearCampos);
        jp_CrearCampos.setLayout(jp_CrearCamposLayout);
        jp_CrearCamposLayout.setHorizontalGroup(
            jp_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_ListarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_CrearCamposLayout.createSequentialGroup()
                    .addGap(139, 139, 139)
                    .addGroup(jp_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jb_CrearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcb_llavePrimaria)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcb_tipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(js_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_NomCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(140, Short.MAX_VALUE)))
        );
        jp_CrearCamposLayout.setVerticalGroup(
            jp_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_ListarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_CrearCamposLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jtf_NomCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(js_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jcb_tipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jcb_llavePrimaria)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                    .addComponent(jb_CrearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)))
        );

        javax.swing.GroupLayout jd_CamposLayout = new javax.swing.GroupLayout(jd_Campos.getContentPane());
        jd_Campos.getContentPane().setLayout(jd_CamposLayout);
        jd_CamposLayout.setHorizontalGroup(
            jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CamposLayout.createSequentialGroup()
                .addComponent(jp_CrearCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jd_CamposLayout.setVerticalGroup(
            jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jp_CrearCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Estru II");

        jPanel1.setBackground(new java.awt.Color(175, 175, 255));

        jb_Archivos.setBackground(new java.awt.Color(125, 125, 241));
        jb_Archivos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_Archivos.setForeground(new java.awt.Color(22, 22, 79));
        jb_Archivos.setText("Archivos");
        jb_Archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ArchivosMouseClicked(evt);
            }
        });
        jb_Archivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_ArchivosKeyPressed(evt);
            }
        });

        jb_Campos.setBackground(new java.awt.Color(125, 125, 241));
        jb_Campos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_Campos.setForeground(new java.awt.Color(22, 22, 79));
        jb_Campos.setText("Campos");
        jb_Campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CamposMouseClicked(evt);
            }
        });

        jb_Registros.setBackground(new java.awt.Color(125, 125, 241));
        jb_Registros.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_Registros.setForeground(new java.awt.Color(22, 22, 79));
        jb_Registros.setText("Registros");

        jb_Indices.setBackground(new java.awt.Color(125, 125, 241));
        jb_Indices.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_Indices.setForeground(new java.awt.Color(22, 22, 79));
        jb_Indices.setText("Indices");

        jb_CerrarPrograma.setText("Cerrar Programa");
        jb_CerrarPrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CerrarProgramaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 301, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jb_Archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Campos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Indices, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(298, 298, 298))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jb_CerrarPrograma)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_CerrarPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_Archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Campos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Indices, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jb_Archivos1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_Archivos1KeyPressed

    }//GEN-LAST:event_jb_Archivos1KeyPressed

    private void jb_Archivos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Archivos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_Archivos1ActionPerformed

    private void jb_Archivos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_Archivos1MouseClicked


    }//GEN-LAST:event_jb_Archivos1MouseClicked

    private void jb_ArchivosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_ArchivosKeyPressed

    }//GEN-LAST:event_jb_ArchivosKeyPressed

    private void jb_ArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ArchivosMouseClicked
        this.setVisible(false);
        jd_Archivos.setModal(true);
        jd_Archivos.pack();
        jd_Archivos.setLocationRelativeTo(this);
        jd_Archivos.setVisible(true);
    }//GEN-LAST:event_jb_ArchivosMouseClicked

    private void jtf_NomCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomCampo1ActionPerformed

    private void jtf_NomCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomCampo2ActionPerformed

    private void jtf_NomCampo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomCampo3ActionPerformed

    private void jtf_NomCampo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomCampo4ActionPerformed

    private void jtf_NomCampo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomCampo5ActionPerformed

    private void jtf_NomCampo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomCampo6ActionPerformed

    private void jtf_NomCampo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomCampo7ActionPerformed

    private void jtf_NomCampo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampo8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomCampo8ActionPerformed

    private void jtf_NomCampo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampo9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomCampo9ActionPerformed

    private void jtf_NomCampo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampo10ActionPerformed

    }//GEN-LAST:event_jtf_NomCampo10ActionPerformed

    private void jb_CerrarProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CerrarProgramaMouseClicked
//        this.setVisible(false);
//        jd_CrearCampos.setModal(true);
//        jd_CrearCampos.pack();
//        jd_CrearCampos.setLocationRelativeTo(this);
//        jd_CrearCampos.setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_jb_CerrarProgramaMouseClicked

    private void jb_CerrarPrograma1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CerrarPrograma1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_CerrarPrograma1MouseClicked

    private void jb_GuardarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_GuardarCamposMouseClicked

    }//GEN-LAST:event_jb_GuardarCamposMouseClicked

    private void jb_crearCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCampoMouseClicked
        //Prepara para crear Campos
        //setea los text fields vacios
//        jtf_NomCampo1.setText("");jtf_NomCampo2.setText("");
//        jtf_NomCampo3.setText("");jtf_NomCampo4.setText("");
//        jtf_NomCampo5.setText("");jtf_NomCampo6.setText("");
//        jtf_NomCampo7.setText("");jtf_NomCampo8.setText("");
//        jtf_NomCampo9.setText("");jtf_NomCampo10.setText("");
//        //todos los botones son deseleccionados
//        jrb_llavePrimaria1.setSelected(true);
//        //setea los spinners a 0
//        js_longitud1.setValue(0);js_longitud2.setValue(0);
//        js_longitud3.setValue(0);js_longitud4.setValue(0);
//        js_longitud5.setValue(0);js_longitud6.setValue(0);
//        js_longitud7.setValue(0);js_longitud8.setValue(0);
//        js_longitud9.setValue(0);js_longitud10.setValue(0);
//        //setea los combo boxes a boolean
//        jcb_tipoDato1.setSelectedItem("Boolean");jcb_tipoDato2.setSelectedItem("Boolean");
//        jcb_tipoDato3.setSelectedItem("Boolean");jcb_tipoDato4.setSelectedItem("Boolean");
//        jcb_tipoDato5.setSelectedItem("Boolean");jcb_tipoDato6.setSelectedItem("Boolean");
//        jcb_tipoDato7.setSelectedItem("Boolean");jcb_tipoDato8.setSelectedItem("Boolean");
//        jcb_tipoDato9.setSelectedItem("Boolean");jcb_tipoDato10.setSelectedItem("Boolean");

        jtf_NomCampo.setText("");
        jcb_tipoDato.setSelectedItem("Boolean");
        js_longitud.setValue(0);
        jcb_llavePrimaria.setSelected(false);

        jp_CrearCampos.setVisible(true);
        jp_ListarCampos.setVisible(false);
        jp_ModificarCampos.setVisible(false);
        jp_BorrarCampos.setVisible(false);
        jp_Vacio.setVisible(false);
    }//GEN-LAST:event_jb_crearCampoMouseClicked

    private void jb_crearCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_crearCampoActionPerformed

    private void jb_crearCampoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_crearCampoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_crearCampoKeyPressed

    private void jb_CerrarPrograma2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CerrarPrograma2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jb_CerrarPrograma2MouseClicked

    private void jb_CamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CamposMouseClicked
        this.setVisible(false);
        jd_Campos.setModal(true);
        jd_Campos.pack();
        jd_Campos.setLocationRelativeTo(this);
        jd_Campos.setVisible(true);
    }//GEN-LAST:event_jb_CamposMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jd_CrearCampos.setVisible(false);
        jd_Campos.setModal(true);
        jd_Campos.pack();
        jd_Campos.setLocationRelativeTo(this);
        jd_Campos.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_GuardarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_GuardarCamposActionPerformed
        boolean check = true; //se pone falso cuando las validaciones detectan algo malo

        //verifica si los campos estan vacios
//        if(jtf_NomCampo1.getText().equals("")&&jtf_NomCampo2.getText().equals("")&&jtf_NomCampo3.getText().equals("")&&jtf_NomCampo4.getText().equals("")&&
//                jtf_NomCampo5.getText().equals("")&&jtf_NomCampo6.getText().equals("")&&jtf_NomCampo7.getText().equals("")&&jtf_NomCampo8.getText().equals("")&&
//                jtf_NomCampo9.getText().equals("")&&jtf_NomCampo10.getText().equals("")){
//            JOptionPane.showMessageDialog(rootPane, "Tiene que crear al menos un campo");
//            check = false;
//        }
//        if(jtf_NomCampo1.getText().equals("") == false && jrb_llavePrimaria1.isSelected() || jtf_NomCampo2.getText().equals("") == false && jrb_llavePrimaria2.isSelected() ||
//                jtf_NomCampo3.getText().equals("") == false && jrb_llavePrimaria3.isSelected() || jtf_NomCampo4.getText().equals("") == false && jrb_llavePrimaria4.isSelected() ||
//                jtf_NomCampo5.getText().equals("") == false && jrb_llavePrimaria5.isSelected() || jtf_NomCampo6.getText().equals("") == false && jrb_llavePrimaria6.isSelected() ||
//                jtf_NomCampo7.getText().equals("") == false && jrb_llavePrimaria7.isSelected() || jtf_NomCampo8.getText().equals("") == false && jrb_llavePrimaria8.isSelected() ||
//                jtf_NomCampo9.getText().equals("") == false && jrb_llavePrimaria9.isSelected() || jtf_NomCampo10.getText().equals("") == false && jrb_llavePrimaria10.isSelected()){
//        }else{
//            JOptionPane.showMessageDialog(rootPane, "Tiene que elegir un campo que sea la llave primaria");
//            check = false;
//        }
//        if(jtf_NomCampo1.getText().equals("") == false && (Integer)js_longitud1.getValue() < 1 || jtf_NomCampo2.getText().equals("") == false && (Integer)js_longitud2.getValue() < 1 ||
//                jtf_NomCampo3.getText().equals("") == false && (Integer)js_longitud3.getValue() < 1 || jtf_NomCampo4.getText().equals("") == false && (Integer)js_longitud4.getValue() < 1 ||
//                jtf_NomCampo5.getText().equals("") == false && (Integer)js_longitud5.getValue() < 1 || jtf_NomCampo6.getText().equals("") == false && (Integer)js_longitud6.getValue() < 1 ||
//                jtf_NomCampo7.getText().equals("") == false && (Integer)js_longitud7.getValue() < 1 || jtf_NomCampo8.getText().equals("") == false && (Integer)js_longitud8.getValue() < 1 ||
//                jtf_NomCampo9.getText().equals("") == false && (Integer)js_longitud9.getValue() < 1 || jtf_NomCampo10.getText().equals("") == false && (Integer)js_longitud10.getValue() < 1){
//            JOptionPane.showMessageDialog(rootPane, "No puede tener una longitud de 0 o menos");
//            check = false;
//        }
//    
//        if(check){
//            if(jtf_NomCampo1.getText().equals("") == false){
//                Campos.add(new Campo(jtf_NomCampo1.getText(), (String)jcb_tipoDato1.getSelectedItem(), (int)js_longitud1.getValue(), jrb_llavePrimaria1.isSelected()));
//            }
//            if(jtf_NomCampo2.getText().equals("") == false){
//                Campos.add(new Campo(jtf_NomCampo2.getText(), (String)jcb_tipoDato2.getSelectedItem(), (int)js_longitud2.getValue(), jrb_llavePrimaria2.isSelected()));
//            }
//            if(jtf_NomCampo3.getText().equals("") == false){
//                Campos.add(new Campo(jtf_NomCampo3.getText(), (String)jcb_tipoDato3.getSelectedItem(), (int)js_longitud3.getValue(), jrb_llavePrimaria3.isSelected()));
//            }
//            if(jtf_NomCampo4.getText().equals("") == false){
//                Campos.add(new Campo(jtf_NomCampo4.getText(), (String)jcb_tipoDato4.getSelectedItem(), (int)js_longitud4.getValue(), jrb_llavePrimaria4.isSelected()));
//            }
//            if(jtf_NomCampo5.getText().equals("") == false){
//                Campos.add(new Campo(jtf_NomCampo5.getText(), (String)jcb_tipoDato5.getSelectedItem(), (int)js_longitud5.getValue(), jrb_llavePrimaria5.isSelected()));
//            }
//            if(jtf_NomCampo6.getText().equals("") == false){
//                Campos.add(new Campo(jtf_NomCampo6.getText(), (String)jcb_tipoDato6.getSelectedItem(), (int)js_longitud6.getValue(), jrb_llavePrimaria6.isSelected()));
//            }
//            if(jtf_NomCampo7.getText().equals("") == false){
//                Campos.add(new Campo(jtf_NomCampo7.getText(), (String)jcb_tipoDato7.getSelectedItem(), (int)js_longitud7.getValue(), jrb_llavePrimaria7.isSelected()));
//            }
//            if(jtf_NomCampo8.getText().equals("") == false){
//                Campos.add(new Campo(jtf_NomCampo8.getText(), (String)jcb_tipoDato8.getSelectedItem(), (int)js_longitud8.getValue(), jrb_llavePrimaria8.isSelected()));
//            }
//            if(jtf_NomCampo9.getText().equals("") == false){
//                Campos.add(new Campo(jtf_NomCampo9.getText(), (String)jcb_tipoDato9.getSelectedItem(), (int)js_longitud9.getValue(), jrb_llavePrimaria9.isSelected()));
//            }
//            if(jtf_NomCampo10.getText().equals("") == false){
//                Campos.add(new Campo(jtf_NomCampo10.getText(), (String)jcb_tipoDato10.getSelectedItem(), (int)js_longitud10.getValue(), jrb_llavePrimaria10.isSelected()));
//            }
//            for (int i = 0; i < Campos.size(); i++) {
//                System.out.println(Campos.get(i));
//            }
//            System.out.println(Campos.size());
//        }
    }//GEN-LAST:event_jb_GuardarCamposActionPerformed

    private void jrb_llavePrimaria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_llavePrimaria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_llavePrimaria2ActionPerformed

    private void jb_CerrarPrograma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CerrarPrograma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_CerrarPrograma1ActionPerformed

    private void jtf_NomCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_NomCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_NomCampoActionPerformed

    private void jb_Campos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Campos2ActionPerformed
        if (Campos.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "No hay Campos");
        } else {
            DefaultTableModel tm = (DefaultTableModel) jt_ListarCampos.getModel();
            tm.setRowCount(0);
            for (int i = 0; i < Campos.size(); i++) {
                Object[] temp = new Object[4];
                temp[0] = Campos.get(i).getNombre();
                temp[1] = Campos.get(i).getTipo();
                temp[2] = Campos.get(i).getLongitud();
                temp[3] = Campos.get(i).isLlavePrimaria();
                tm.addRow(temp);
            }

            jt_ListarCampos.setModel(tm);
            jp_CrearCampos.setVisible(true);
            jp_ListarCampos.setVisible(true);
            jp_ModificarCampos.setVisible(false);
            jp_BorrarCampos.setVisible(false);
            jp_Vacio.setVisible(false);
        }

    }//GEN-LAST:event_jb_Campos2ActionPerformed

    private void jb_CrearCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearCampoMouseClicked
        if (modificar) {
            
            Campos.get(Campos.indexOf(cam)).setNombre(jtf_NomCampo.getText());
            Campos.get(Campos.indexOf(cam)).setTipo((String)jcb_tipoDato.getSelectedItem());
            Campos.get(Campos.indexOf(cam)).setLongitud((int)js_longitud.getValue());
            if(jcb_llavePrimaria.isSelected()){
                for (int i = 0; i < Campos.size(); i++) {
                    if(Campos.get(i).isLlavePrimaria()){
                        Campos.get(i).setLlavePrimaria(false);
                    }
                }
            }
            Campos.get(Campos.indexOf(cam)).setLlavePrimaria(jcb_llavePrimaria.isSelected());
            
            jtf_NomCampo.setText("");
            jcb_tipoDato.setSelectedItem("Boolean");
            js_longitud.setValue(0);
            jcb_llavePrimaria.setSelected(false);
            
            modificar = false;
            
        } else {
            if (Campos.size() < 10) {
                boolean check = true;
                if (jtf_NomCampo.getText().equals("")) {
                    JOptionPane.showMessageDialog(rootPane, "Tiene que crear al menos un campo");
                    check = false;
                }
                if ((int) js_longitud.getValue() < 1) {
                    JOptionPane.showMessageDialog(rootPane, "La longitud debe ser mas de 0");
                    check = false;
                }

                if (Campos.isEmpty() && jcb_llavePrimaria.isSelected() == false) {
                    jcb_llavePrimaria.setSelected(true);
                } else if (jcb_llavePrimaria.isSelected()) {

                    for (int i = 0; i < Campos.size(); i++) {
                        if (Campos.get(i).isLlavePrimaria()) {
                            Campos.get(i).setLlavePrimaria(false);
                        }
                    }
                }

                if (check) {
                    Campos.add(new Campo(jtf_NomCampo.getText(), (String) jcb_tipoDato.getSelectedItem(), (int) js_longitud.getValue(), jcb_llavePrimaria.isSelected()));
                }

                jtf_NomCampo.setText("");
                jcb_tipoDato.setSelectedItem("Boolean");
                js_longitud.setValue(0);
                jcb_llavePrimaria.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Hay un maximo de 10 Campos");
            }
        }

    }//GEN-LAST:event_jb_CrearCampoMouseClicked

    private void jb_Indices2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Indices2ActionPerformed
        if (Campos.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "No hay Campos");
        } else {
            DefaultListModel lm = new DefaultListModel();
            lm.addAll(Campos);
            jl_Borrar.setModel(lm);
            jp_CrearCampos.setVisible(true);
            jp_ListarCampos.setVisible(true);
            jp_ModificarCampos.setVisible(true);
            jp_BorrarCampos.setVisible(true);
            jp_Vacio.setVisible(false);
        }


    }//GEN-LAST:event_jb_Indices2ActionPerformed

    private void jl_BorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_BorrarMouseClicked

    }//GEN-LAST:event_jl_BorrarMouseClicked

    private void jb_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarActionPerformed
        cam = Campos.get(jl_Borrar.getSelectedIndex());
        Campos.remove(jl_Borrar.getSelectedIndex());
        if (Campos.size() >= 1 && cam.isLlavePrimaria() == true) {
            Campos.get(0).setLlavePrimaria(true);
        }
        DefaultListModel lm = new DefaultListModel();
        lm.addAll(Campos);
        jl_Borrar.setModel(lm);
    }//GEN-LAST:event_jb_borrarActionPerformed

    private void jb_Registros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Registros2ActionPerformed
        if (Campos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay Campos");
        } else {

            DefaultListModel lm = new DefaultListModel();
            lm.addAll(Campos);
            jl_ModificarCampos.setModel(lm);
            jp_CrearCampos.setVisible(true);
            jp_ListarCampos.setVisible(true);
            jp_ModificarCampos.setVisible(true);
            jp_BorrarCampos.setVisible(false);
            jp_Vacio.setVisible(false);
        }
    }//GEN-LAST:event_jb_Registros2ActionPerformed

    private void jl_ModificarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_ModificarCamposMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_ModificarCamposMouseClicked

    private void jb_ModificarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModificarCamposActionPerformed
        cam = Campos.get(jl_ModificarCampos.getSelectedIndex());

        jtf_NomCampo.setText(cam.getNombre());
        jcb_tipoDato.setSelectedItem(cam.getTipo());
        js_longitud.setValue(cam.getLongitud());
        jcb_llavePrimaria.setSelected(cam.isLlavePrimaria());
        jb_CrearCampo.setText("Modificar");

        modificar = true;
        jp_CrearCampos.setVisible(true);
        jp_ListarCampos.setVisible(false);
        jp_ModificarCampos.setVisible(false);
        jp_BorrarCampos.setVisible(false);
        jp_Vacio.setVisible(false);


    }//GEN-LAST:event_jb_ModificarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estru2Proyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estru2Proyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estru2Proyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estru2Proyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estru2Proyect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jb_Archivos;
    private javax.swing.JButton jb_Archivos1;
    private javax.swing.JButton jb_Campos;
    private javax.swing.JButton jb_Campos1;
    private javax.swing.JButton jb_Campos2;
    private javax.swing.JButton jb_CerrarPrograma;
    private javax.swing.JButton jb_CerrarPrograma1;
    private javax.swing.JButton jb_CerrarPrograma2;
    private javax.swing.JButton jb_CrearCampo;
    private javax.swing.JButton jb_GuardarCampos;
    private javax.swing.JButton jb_Indices;
    private javax.swing.JButton jb_Indices1;
    private javax.swing.JButton jb_Indices2;
    private javax.swing.JButton jb_ModificarCampos;
    private javax.swing.JButton jb_Registros;
    private javax.swing.JButton jb_Registros1;
    private javax.swing.JButton jb_Registros2;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_crearCampo;
    private javax.swing.JCheckBox jcb_llavePrimaria;
    private javax.swing.JComboBox<String> jcb_tipoDato;
    private javax.swing.JComboBox<String> jcb_tipoDato1;
    private javax.swing.JComboBox<String> jcb_tipoDato10;
    private javax.swing.JComboBox<String> jcb_tipoDato2;
    private javax.swing.JComboBox<String> jcb_tipoDato3;
    private javax.swing.JComboBox<String> jcb_tipoDato4;
    private javax.swing.JComboBox<String> jcb_tipoDato5;
    private javax.swing.JComboBox<String> jcb_tipoDato6;
    private javax.swing.JComboBox<String> jcb_tipoDato7;
    private javax.swing.JComboBox<String> jcb_tipoDato8;
    private javax.swing.JComboBox<String> jcb_tipoDato9;
    private javax.swing.JDialog jd_Archivos;
    private javax.swing.JDialog jd_Campos;
    private javax.swing.JDialog jd_CrearCampos;
    private javax.swing.JList<Campo> jl_Borrar;
    private javax.swing.JList<Campo> jl_ModificarCampos;
    private javax.swing.JPanel jp_BorrarCampos;
    private javax.swing.JPanel jp_CrearCampos;
    private javax.swing.JPanel jp_ListarCampos;
    private javax.swing.JPanel jp_ModificarCampos;
    private javax.swing.JPanel jp_Vacio;
    private javax.swing.JRadioButton jrb_llavePrimaria1;
    private javax.swing.JRadioButton jrb_llavePrimaria10;
    private javax.swing.JRadioButton jrb_llavePrimaria2;
    private javax.swing.JRadioButton jrb_llavePrimaria3;
    private javax.swing.JRadioButton jrb_llavePrimaria4;
    private javax.swing.JRadioButton jrb_llavePrimaria5;
    private javax.swing.JRadioButton jrb_llavePrimaria6;
    private javax.swing.JRadioButton jrb_llavePrimaria7;
    private javax.swing.JRadioButton jrb_llavePrimaria8;
    private javax.swing.JRadioButton jrb_llavePrimaria9;
    private javax.swing.JSpinner js_longitud;
    private javax.swing.JSpinner js_longitud1;
    private javax.swing.JSpinner js_longitud10;
    private javax.swing.JSpinner js_longitud2;
    private javax.swing.JSpinner js_longitud3;
    private javax.swing.JSpinner js_longitud4;
    private javax.swing.JSpinner js_longitud5;
    private javax.swing.JSpinner js_longitud6;
    private javax.swing.JSpinner js_longitud7;
    private javax.swing.JSpinner js_longitud8;
    private javax.swing.JSpinner js_longitud9;
    private javax.swing.JTable jt_ListarCampos;
    private javax.swing.JTextField jtf_NomCampo;
    private javax.swing.JTextField jtf_NomCampo1;
    private javax.swing.JTextField jtf_NomCampo10;
    private javax.swing.JTextField jtf_NomCampo2;
    private javax.swing.JTextField jtf_NomCampo3;
    private javax.swing.JTextField jtf_NomCampo4;
    private javax.swing.JTextField jtf_NomCampo5;
    private javax.swing.JTextField jtf_NomCampo6;
    private javax.swing.JTextField jtf_NomCampo7;
    private javax.swing.JTextField jtf_NomCampo8;
    private javax.swing.JTextField jtf_NomCampo9;
    // End of variables declaration//GEN-END:variables
    ArrayList<Campo> Campos = new ArrayList();
    Campo cam;
    boolean modificar = false;
}
